name: Publish to PyPI

on:
  push:
    tags:
      - '*'


jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
#        cache-dependency-glob: "uv.lock" # invalidate it when the lockfile changes -> tilo what exactly does this mean?
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build the project
      run: uv build

    - name: Save sdist
      uses: actions/upload-artifact@v4
      with:
        path: dist/*.tar.gz
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    # Don't release when running the workflow manually from GitHub's UI.
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    environment:
      name: pypi
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: artifact
        path: dist
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1